version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - echo Installing dependencies for the python application
      - pip install -r requirements.txt
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 163622408598.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Running tests...
      - pytest
      - echo Building the Docker image...
      - docker build --platform linux/amd64 -t entrega3 .
      - docker tag entrega3:latest 163622408598.dkr.ecr.us-east-1.amazonaws.com/entrega3:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push 163622408598.dkr.ecr.us-east-1.amazonaws.com/entrega3:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"Container-app-python","imageUri":"163622408598.dkr.ecr.us-east-1.amazonaws.com/entrega3:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"163622408598.dkr.ecr.us-east-1.amazonaws.com/entrega3:latest"}' > imageDetail.json
      - cat imagedefinitions.json 
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
