version: '3.8'

services:
  db-blacklist:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  blacklist_app:
    build: .
    container_name: blacklist_app
    restart: always
    depends_on:
      - db-blacklist
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST_DOCKER}:${DB_PORT}/${DB_NAME}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env 

volumes:
  postgres_data: